CREATE ROLE admin_role;
CREATE ROLE user_role;
CREATE ROLE employee_role;

GRANT CONNECT, RESOURCE, DBA TO admin_role;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO admin_role;
GRANT EXECUTE ON DBMS_REDACT TO admin_role;


GRANT CONNECT TO employee_role;
GRANT EXECUTE ON admin.sp_login_user TO employee_role;
GRANT EXECUTE ON admin.sp_get_user_info TO employee_role;
GRANT EXECUTE ON admin.sp_get_user_tickets TO employee_role;
GRANT EXECUTE ON admin.sp_user_search_available_flights TO employee_role;
GRANT EXECUTE ON admin.view_available_tickets TO employee_role;
GRANT EXECUTE ON admin.search_tickets TO employee_role;
GRANT EXECUTE ON admin.book_ticket TO employee_role; 
GRANT EXECUTE ON admin.sp_get_user_tickets TO employee_role;
GRANT EXECUTE ON admin.sp_cancel_ticket_booking TO employee_role;

GRANT EXECUTE ON admin.sp_analyze_tickets_and_routes TO employee_role;
GRANT EXECUTE ON admin.sp_analyze_routes TO employee_role;
GRANT EXECUTE ON admin.sp_analyze_popular_routes TO employee_role;
GRANT EXECUTE ON admin.sp_view_regular_users TO employee_role;
GRANT EXECUTE ON admin.SP_ADD_TICKET_FOR_AIRPORT_FLIGHT TO employee_role;
GRANT EXECUTE ON admin.SP_GET_FLIGHTS_AND_TICKETS_FOR_AIRPORT TO employee_role;
GRANT EXECUTE ON admin.SP_EDIT_TICKET TO employee_role; 
GRANT EXECUTE ON admin.SP_DELETE_TICKET TO employee_role;
GRANT EXECUTE ON admin.sp_add_flight TO employee_role;
GRANT EXECUTE ON admin.sp_update_flight TO employee_role;
GRANT EXECUTE ON admin.sp_view_airport_employees TO employee_role;


GRANT CONNECT TO user_role;
GRANT EXECUTE ON admin.sp_register_user TO user_role;
GRANT EXECUTE ON admin.sp_login_user TO user_role;
GRANT EXECUTE ON admin.sp_get_user_info TO user_role;
GRANT EXECUTE ON admin.sp_get_user_tickets TO user_role;
GRANT EXECUTE ON admin.sp_user_search_available_flights TO user_role;
GRANT EXECUTE ON admin.view_available_tickets TO user_role;
GRANT EXECUTE ON admin.search_tickets TO user_role;
GRANT EXECUTE ON admin.book_ticket TO user_role; 
GRANT EXECUTE ON admin.sp_get_user_tickets TO user_role;
GRANT EXECUTE ON admin.sp_cancel_ticket_booking TO user_role;

CREATE USER admin IDENTIFIED BY password;
GRANT admin_role TO admin;

CREATE USER PAS IDENTIFIED BY password;
GRANT admin_role TO PAS;
ALTER USER PAS QUOTA UNLIMITED ON USERS;

GRANT EXECUTE ON SYS.DBMS_CRYPTO TO admin;


CREATE USER app_user IDENTIFIED BY password;
GRANT user_role TO app_user;

CREATE USER employee_user IDENTIFIED BY password;
GRANT employee_role TO employee_user;


CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    user_password VARCHAR2(100) NOT NULL, -- "password" -> "user_password"
    passport_number VARCHAR2(100) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    phone VARCHAR2(20) UNIQUE,
    is_active NUMBER(1) DEFAULT 1, -- 1 for TRUE, 0 for FALSE
    firstname VARCHAR2(100) NOT NULL,
    lastname VARCHAR2(100) NOT NULL,
    birthdate DATE NOT NULL,
    country VARCHAR2(50),
    city VARCHAR2(50),
    street VARCHAR2(100)
);

CREATE TABLE Airports (
    airport_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iata_code CHAR(3) UNIQUE NOT NULL,
    airport_name VARCHAR2(100) NOT NULL, -- "name" -> "airport_name"
    city VARCHAR2(50) NOT NULL,
    country VARCHAR2(50) NOT NULL
);

CREATE TABLE Employee (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES Users(user_id), -- Links to Users table for personal details
    airport_id NOT NULL REFERENCES Airports(airport_id), -- Links to their assigned airport
    job_title VARCHAR2(50) NOT NULL,
    hire_date DATE NOT NULL,
    salary NUMBER NOT NULL
);



CREATE TABLE Airplane_Types (
    type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airplane_model VARCHAR2(50) UNIQUE NOT NULL,
    manufacturer VARCHAR2(50) NOT NULL,
    seating_capacity SMALLINT NOT NULL CHECK (seating_capacity > 0),
    airplane_description VARCHAR2(200)
);


CREATE TABLE Airlines (
    airline_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iata_code CHAR(2) UNIQUE NOT NULL,
    airline_name VARCHAR2(100) NOT NULL, -- "name" -> "airline_name"
    country VARCHAR2(50) NOT NULL,
    base_airport_id NUMBER REFERENCES Airports(airport_id)
);

CREATE TABLE Airplanes (
    airplane_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id NUMBER NOT NULL REFERENCES Airplane_Types(type_id),
    airline_id NUMBER NOT NULL REFERENCES Airlines(airline_id),
    tail_number VARCHAR2(20) UNIQUE NOT NULL,
    airplane_status VARCHAR2(20) DEFAULT 'Active' CHECK (airplane_status IN ('Active', 'Maintenance', 'Retired')) -- "status" -> "airplane_status"
);

CREATE TABLE Flights (
    flight_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR2(20) UNIQUE,
    departure_airport_id NUMBER NOT NULL REFERENCES Airports(airport_id),
    arrival_airport_id NUMBER NOT NULL REFERENCES Airports(airport_id),
    departure_time TIMESTAMP NOT NULL,
    arrival_time TIMESTAMP NOT NULL,
    airline_id NUMBER NOT NULL REFERENCES Airlines(airline_id),
    airplane_id NUMBER NOT NULL REFERENCES Airplanes(airplane_id),
    flight_status VARCHAR2(20) DEFAULT 'Scheduled' CHECK (flight_status IN ('Scheduled', 'Departed', 'In Air', 'Landed', 'Cancelled'))
    
);

CREATE TABLE Tickets (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number VARCHAR2(20) UNIQUE,
    flight_id NUMBER NOT NULL REFERENCES Flights(flight_id),
    passenger_id NUMBER DEFAULT NULL REFERENCES Users(user_id),
    seat_number VARCHAR2(5) NOT NULL,
    price NUMBER NOT NULL,
    purchase_date TIMESTAMP DEFAULT NULL,
    ticket_class VARCHAR2(20) DEFAULT 'Economy' CHECK (ticket_class IN ('Economy', 'Business', 'First')), -- "class" -> "ticket_class"
    ticket_status VARCHAR2(20) DEFAULT 'Available' CHECK (ticket_status IN ('Booked', 'Available', 'Completed')), -- "status" -> "ticket_status"
    CONSTRAINT unique_flight_seat UNIQUE (flight_id, seat_number)
);

DROP TABLE Tickets; 
DROP TABLE Flights;
DROP TABLE Airplanes;
DROP TABLE Airlines;
DROP TABLE Airplane_Types;
DROP TABLE Airports CASCADE CONSTRAINTS;
DROP TABLE Employee;
DROP TABLE Users;


-- Очистка таблиц в правильном порядке
DELETE FROM Tickets;
DELETE FROM Flights;
DELETE FROM Airplanes;
DELETE FROM Airlines;
DELETE FROM Airplane_Types;
DELETE FROM Employee;
DELETE FROM Airports;
DELETE FROM Users;

SELECT * FROM Tickets;
SELECT * FROM Flights;
SELECT * FROM Airplanes;
SELECT * FROM Airlines;
SELECT * FROM Airplane_Types;
SELECT * FROM Employee;
SELECT * FROM Airports;
SELECT * FROM Users;

-- Опционально: Сбросить последовательности
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE Tickets MODIFY ticket_id GENERATED BY DEFAULT AS IDENTITY (START WITH 1)';
    EXECUTE IMMEDIATE 'ALTER TABLE Flights MODIFY flight_id GENERATED BY DEFAULT AS IDENTITY (START WITH 1)';
    EXECUTE IMMEDIATE 'ALTER TABLE Airplanes MODIFY airplane_id GENERATED BY DEFAULT AS IDENTITY (START WITH 1)';
    EXECUTE IMMEDIATE 'ALTER TABLE Airlines MODIFY airline_id GENERATED BY DEFAULT AS IDENTITY (START WITH 1)';
    EXECUTE IMMEDIATE 'ALTER TABLE Airplane_Types MODIFY type_id GENERATED BY DEFAULT AS IDENTITY (START WITH 1)';
    EXECUTE IMMEDIATE 'ALTER TABLE Employee MODIFY employee_id GENERATED BY DEFAULT AS IDENTITY (START WITH 1)';
    EXECUTE IMMEDIATE 'ALTER TABLE Airports MODIFY airport_id GENERATED BY DEFAULT AS IDENTITY (START WITH 1)';
    EXECUTE IMMEDIATE 'ALTER TABLE Users MODIFY user_id GENERATED BY DEFAULT AS IDENTITY (START WITH 1)';
END;
/


INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user1', 
    pkg_crypto_utils.encrypt_data('password1'), 
    pkg_crypto_utils.encrypt_data('P123456'), 
    'user1@example.com', 
    '5551234561', 
    pkg_crypto_utils.encrypt_data('Alice'), 
    pkg_crypto_utils.encrypt_data('Smith'), 
    TO_DATE('1990-01-01', 'YYYY-MM-DD'), 
    'USA', 
    pkg_crypto_utils.encrypt_data('New York'), 
    pkg_crypto_utils.encrypt_data('1st Avenue')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user2', 
    pkg_crypto_utils.encrypt_data('password2'), 
    pkg_crypto_utils.encrypt_data('P234567'), 
    'user2@example.com', 
    '5551234562', 
    pkg_crypto_utils.encrypt_data('Bob'), 
    pkg_crypto_utils.encrypt_data('Brown'), 
    TO_DATE('1991-02-01', 'YYYY-MM-DD'), 
    'Canada', 
    pkg_crypto_utils.encrypt_data('Toronto'), 
    pkg_crypto_utils.encrypt_data('2nd Street')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user3', 
    pkg_crypto_utils.encrypt_data('password3'), 
    pkg_crypto_utils.encrypt_data('P345678'), 
    'user3@example.com', 
    '5551234563', 
    pkg_crypto_utils.encrypt_data('Charlie'), 
    pkg_crypto_utils.encrypt_data('Davis'), 
    TO_DATE('1992-03-01', 'YYYY-MM-DD'), 
    'UK', 
    pkg_crypto_utils.encrypt_data('London'), 
    pkg_crypto_utils.encrypt_data('3rd Boulevard')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user4', 
    pkg_crypto_utils.encrypt_data('password4'), 
    pkg_crypto_utils.encrypt_data('P456789'), 
    'user4@example.com', 
    '5551234564', 
    pkg_crypto_utils.encrypt_data('Diana'), 
    pkg_crypto_utils.encrypt_data('Evans'), 
    TO_DATE('1993-04-01', 'YYYY-MM-DD'), 
    'Australia', 
    pkg_crypto_utils.encrypt_data('Sydney'), 
    pkg_crypto_utils.encrypt_data('4th Road')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user5', 
    pkg_crypto_utils.encrypt_data('password5'), 
    pkg_crypto_utils.encrypt_data('P567890'), 
    'user5@example.com', 
    '5551234565', 
    pkg_crypto_utils.encrypt_data('Eve'), 
    pkg_crypto_utils.encrypt_data('Foster'), 
    TO_DATE('1994-05-01', 'YYYY-MM-DD'), 
    'Germany', 
    pkg_crypto_utils.encrypt_data('Berlin'), 
    pkg_crypto_utils.encrypt_data('5th Lane')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user6', 
    pkg_crypto_utils.encrypt_data('password6'), 
    pkg_crypto_utils.encrypt_data('P678901'), 
    'user6@example.com', 
    '5551234566', 
    pkg_crypto_utils.encrypt_data('Frank'), 
    pkg_crypto_utils.encrypt_data('Green'), 
    TO_DATE('1995-06-01', 'YYYY-MM-DD'), 
    'France', 
    pkg_crypto_utils.encrypt_data('Paris'), 
    pkg_crypto_utils.encrypt_data('6th Path')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user7', 
    pkg_crypto_utils.encrypt_data('password7'), 
    pkg_crypto_utils.encrypt_data('P789012'), 
    'user7@example.com', 
    '5551234567', 
    pkg_crypto_utils.encrypt_data('Grace'), 
    pkg_crypto_utils.encrypt_data('Harris'), 
    TO_DATE('1996-07-01', 'YYYY-MM-DD'), 
    'Italy', 
    pkg_crypto_utils.encrypt_data('Rome'), 
    pkg_crypto_utils.encrypt_data('7th Square')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user8', 
    pkg_crypto_utils.encrypt_data('password8'), 
    pkg_crypto_utils.encrypt_data('P890123'), 
    'user8@example.com', 
    '5551234568', 
    pkg_crypto_utils.encrypt_data('Hank'), 
    pkg_crypto_utils.encrypt_data('Irwin'), 
    TO_DATE('1997-08-01', 'YYYY-MM-DD'), 
    'Spain', 
    pkg_crypto_utils.encrypt_data('Madrid'), 
    pkg_crypto_utils.encrypt_data('8th Circle')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user9', 
    pkg_crypto_utils.encrypt_data('password9'), 
    pkg_crypto_utils.encrypt_data('P901234'), 
    'user9@example.com', 
    '5551234569', 
    pkg_crypto_utils.encrypt_data('Ivy'), 
    pkg_crypto_utils.encrypt_data('Johnson'), 
    TO_DATE('1998-09-01', 'YYYY-MM-DD'), 
    'Japan', 
    pkg_crypto_utils.encrypt_data('Tokyo'), 
    pkg_crypto_utils.encrypt_data('9th Alley')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user10', 
    pkg_crypto_utils.encrypt_data('password10'), 
    pkg_crypto_utils.encrypt_data('P012345'), 
    'user10@example.com', 
    '5551234570', 
    pkg_crypto_utils.encrypt_data('Jack'), 
    pkg_crypto_utils.encrypt_data('King'), 
    TO_DATE('1999-10-01', 'YYYY-MM-DD'), 
    'India', 
    pkg_crypto_utils.encrypt_data('Delhi'), 
    pkg_crypto_utils.encrypt_data('10th Avenue')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user11', 
    pkg_crypto_utils.encrypt_data('password11'), 
    pkg_crypto_utils.encrypt_data('PA123456'), 
    'user11@example.com', 
    '5551234581', 
    pkg_crypto_utils.encrypt_data('Alice'), 
    pkg_crypto_utils.encrypt_data('Wonder'), 
    TO_DATE('1990-05-12', 'YYYY-MM-DD'), 
    'USA', 
    pkg_crypto_utils.encrypt_data('New York'), 
    pkg_crypto_utils.encrypt_data('5th Avenue')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user12', 
    pkg_crypto_utils.encrypt_data('password12'), 
    pkg_crypto_utils.encrypt_data('PB789012'), 
    'user12@example.com', 
    '5551234582', 
    pkg_crypto_utils.encrypt_data('Bob'), 
    pkg_crypto_utils.encrypt_data('Marley'), 
    TO_DATE('1985-11-25', 'YYYY-MM-DD'), 
    'Canada', 
    pkg_crypto_utils.encrypt_data('Toronto'), 
    pkg_crypto_utils.encrypt_data('Queen Street')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user13', 
    pkg_crypto_utils.encrypt_data('password13'), 
    pkg_crypto_utils.encrypt_data('PC345678'), 
    'user13@example.com', 
    '5551234583', 
    pkg_crypto_utils.encrypt_data('Charlie'), 
    pkg_crypto_utils.encrypt_data('Brown'), 
    TO_DATE('1995-02-14', 'YYYY-MM-DD'), 
    'UK', 
    pkg_crypto_utils.encrypt_data('London'), 
    pkg_crypto_utils.encrypt_data('Baker Street')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user14', 
    pkg_crypto_utils.encrypt_data('password14'), 
    pkg_crypto_utils.encrypt_data('PD901234'), 
    'user14@example.com', 
    '5551234584', 
    pkg_crypto_utils.encrypt_data('Diana'), 
    pkg_crypto_utils.encrypt_data('Prince'), 
    TO_DATE('1992-03-18', 'YYYY-MM-DD'), 
    'Australia', 
    pkg_crypto_utils.encrypt_data('Sydney'), 
    pkg_crypto_utils.encrypt_data('George Street')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country, city, street)
VALUES (
    'user15', 
    pkg_crypto_utils.encrypt_data('password15'), 
    pkg_crypto_utils.encrypt_data('PE567890'), 
    'user15@example.com', 
    '5551234585', 
    pkg_crypto_utils.encrypt_data('Eve'), 
    pkg_crypto_utils.encrypt_data('Adams'), 
    TO_DATE('1988-08-08', 'YYYY-MM-DD'), 
    'Germany', 
    pkg_crypto_utils.encrypt_data('Berlin'), 
    pkg_crypto_utils.encrypt_data('Alexanderplatz')
);

INSERT INTO Users (username, user_password, passport_number, email, phone, firstname, lastname, birthdate, country)
VALUES (
    'user16', 
    pkg_crypto_utils.encrypt_data('password16'), 
    pkg_crypto_utils.encrypt_data('PF567890'), 
    'user16@example.com', 
    '5551234586', 
    pkg_crypto_utils.encrypt_data('Bob'), 
    pkg_crypto_utils.encrypt_data('Marley'), 
    TO_DATE('2005-08-08', 'YYYY-MM-DD'), 
    'Spain'
);




INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('JFK', 'John F. Kennedy International', 'New York', 'USA');

INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('YYZ', 'Toronto Pearson International', 'Toronto', 'Canada');

INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('LHR', 'London Heathrow', 'London', 'UK');

INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('SYD', 'Sydney Kingsford Smith', 'Sydney', 'Australia');

INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('BER', 'Berlin Brandenburg', 'Berlin', 'Germany');

INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('CDG', 'Charles de Gaulle', 'Paris', 'France');

INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('FCO', 'Leonardo da Vinci', 'Rome', 'Italy');

INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('MAD', 'Adolfo Suarez Madrid-Barajas', 'Madrid', 'Spain');

INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('HND', 'Tokyo Haneda', 'Tokyo', 'Japan');

INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('DEL', 'Indira Gandhi International', 'Delhi', 'India');

INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('DXB', 'Dubai International', 'Dubai', 'UAE');

INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('SIN', 'Changi Airport', 'Singapore', 'Singapore');

INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('HKG', 'Hong Kong International', 'Hong Kong', 'China');

INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('LAX', 'Los Angeles International', 'Los Angeles', 'USA');

INSERT INTO Airports (iata_code, airport_name, city, country)
VALUES ('BOM', 'Chhatrapati Shivaji Maharaj International', 'Mumbai', 'India');



INSERT INTO Airplane_Types (airplane_model, manufacturer, seating_capacity, airplane_description)
VALUES ('Boeing 737', 'Boeing', 189, 'Narrow-body airliner used for short to medium-haul flights');

INSERT INTO Airplane_Types (airplane_model, manufacturer, seating_capacity, airplane_description)
VALUES ('Boeing 777', 'Boeing', 396, 'Wide-body airliner used for long-haul flights');

INSERT INTO Airplane_Types (airplane_model, manufacturer, seating_capacity, airplane_description)
VALUES ('Airbus A320', 'Airbus', 180, 'Narrow-body airliner popular for short to medium-haul routes');

INSERT INTO Airplane_Types (airplane_model, manufacturer, seating_capacity, airplane_description)
VALUES ('Airbus A380', 'Airbus', 853, 'Double-deck, wide-body aircraft; largest passenger plane');

INSERT INTO Airplane_Types (airplane_model, manufacturer, seating_capacity, airplane_description)
VALUES ('Embraer E195', 'Embraer', 132, 'Regional jet for short-haul routes');

INSERT INTO Airplane_Types (airplane_model, manufacturer, seating_capacity, airplane_description)
VALUES ('Bombardier CRJ900', 'Bombardier', 90, 'Regional jet designed for shorter flights');

INSERT INTO Airplane_Types (airplane_model, manufacturer, seating_capacity, airplane_description)
VALUES ('McDonnell Douglas MD-11', 'McDonnell Douglas', 293, 'Wide-body airliner used for both passengers and cargo');

INSERT INTO Airplane_Types (airplane_model, manufacturer, seating_capacity, airplane_description)
VALUES ('Boeing 787', 'Boeing', 330, 'Dreamliner; fuel-efficient wide-body airliner for long-haul');

INSERT INTO Airplane_Types (airplane_model, manufacturer, seating_capacity, airplane_description)
VALUES ('Airbus A330', 'Airbus', 277, 'Wide-body airliner for medium to long-haul flights');

INSERT INTO Airplane_Types (airplane_model, manufacturer, seating_capacity, airplane_description)
VALUES ('Concorde', 'Aerospatiale/BAC', 92, 'Supersonic passenger jet, retired in 2003');

INSERT INTO Airplane_Types (airplane_model, manufacturer, seating_capacity, airplane_description)
VALUES ('Concorde1', 'Aerospatiale/BAC', 2, 'Supersonic passenger jet, retired in 2003');


INSERT INTO Airlines (iata_code, airline_name, country, base_airport_id)
VALUES ('AA', 'American Airlines', 'USA', (SELECT airport_id FROM Airports WHERE iata_code = 'JFK'));

SELECT airport_id FROM Airports WHERE iata_code = 'JFK';
INSERT INTO Airlines (iata_code, airline_name, country, base_airport_id)
VALUES ('AC', 'Air Canada', 'Canada', (SELECT airport_id FROM Airports WHERE iata_code = 'YYZ'));

INSERT INTO Airlines (iata_code, airline_name, country, base_airport_id)
VALUES ('BA', 'British Airways', 'UK', (SELECT airport_id FROM Airports WHERE iata_code = 'LHR'));

INSERT INTO Airlines (iata_code, airline_name, country, base_airport_id)
VALUES ('QF', 'Qantas Airways', 'Australia', (SELECT airport_id FROM Airports WHERE iata_code = 'SYD'));

INSERT INTO Airlines (iata_code, airline_name, country, base_airport_id)
VALUES ('LH', 'Lufthansa', 'Germany', (SELECT airport_id FROM Airports WHERE iata_code = 'BER'));

INSERT INTO Airlines (iata_code, airline_name, country, base_airport_id)
VALUES ('AF', 'Air France', 'France', (SELECT airport_id FROM Airports WHERE iata_code = 'CDG'));

INSERT INTO Airlines (iata_code, airline_name, country, base_airport_id)
VALUES ('AZ', 'Alitalia', 'Italy', (SELECT airport_id FROM Airports WHERE iata_code = 'FCO'));

INSERT INTO Airlines (iata_code, airline_name, country, base_airport_id)
VALUES ('IB', 'Iberia', 'Spain', (SELECT airport_id FROM Airports WHERE iata_code = 'MAD'));

INSERT INTO Airlines (iata_code, airline_name, country, base_airport_id)
VALUES ('JL', 'Japan Airlines', 'Japan', (SELECT airport_id FROM Airports WHERE iata_code = 'HND'));

INSERT INTO Airlines (iata_code, airline_name, country, base_airport_id)
VALUES ('AI', 'Air India', 'India', (SELECT airport_id FROM Airports WHERE iata_code = 'DEL'));


INSERT INTO Airplanes (type_id, airline_id, tail_number, airplane_status)
VALUES ((SELECT type_id FROM Airplane_Types WHERE airplane_model = 'Boeing 737'),
        (SELECT airline_id FROM Airlines WHERE iata_code = 'AA'), 
        'N737AA', 'Active');

INSERT INTO Airplanes (type_id, airline_id, tail_number, airplane_status)
VALUES ((SELECT type_id FROM Airplane_Types WHERE airplane_model = 'Airbus A320'),
        (SELECT airline_id FROM Airlines WHERE iata_code = 'AC'), 
        'C320AC', 'Active');

INSERT INTO Airplanes (type_id, airline_id, tail_number, airplane_status)
VALUES ((SELECT type_id FROM Airplane_Types WHERE airplane_model = 'Boeing 777'),
        (SELECT airline_id FROM Airlines WHERE iata_code = 'BA'), 
        'G777BA', 'Maintenance');

INSERT INTO Airplanes (type_id, airline_id, tail_number, airplane_status)
VALUES ((SELECT type_id FROM Airplane_Types WHERE airplane_model = 'Airbus A380'),
        (SELECT airline_id FROM Airlines WHERE iata_code = 'QF'), 
        'VH380QF', 'Active');

INSERT INTO Airplanes (type_id, airline_id, tail_number, airplane_status)
VALUES ((SELECT type_id FROM Airplane_Types WHERE airplane_model = 'Boeing 787'),
        (SELECT airline_id FROM Airlines WHERE iata_code = 'LH'), 
        'D787LH', 'Active');

INSERT INTO Airplanes (type_id, airline_id, tail_number, airplane_status)
VALUES ((SELECT type_id FROM Airplane_Types WHERE airplane_model = 'Bombardier CRJ900'),
        (SELECT airline_id FROM Airlines WHERE iata_code = 'AF'), 
        'FCRJAF', 'Maintenance');

INSERT INTO Airplanes (type_id, airline_id, tail_number, airplane_status)
VALUES ((SELECT type_id FROM Airplane_Types WHERE airplane_model = 'McDonnell Douglas MD-11'),
        (SELECT airline_id FROM Airlines WHERE iata_code = 'AZ'), 
        'IMD11AZ', 'Active');

INSERT INTO Airplanes (type_id, airline_id, tail_number, airplane_status)
VALUES ((SELECT type_id FROM Airplane_Types WHERE airplane_model = 'Embraer E195'),
        (SELECT airline_id FROM Airlines WHERE iata_code = 'IB'), 
        'EC195IB', 'Retired');

INSERT INTO Airplanes (type_id, airline_id, tail_number, airplane_status)
VALUES ((SELECT type_id FROM Airplane_Types WHERE airplane_model = 'Airbus A330'),
        (SELECT airline_id FROM Airlines WHERE iata_code = 'JL'), 
        'JA330JL', 'Active');

INSERT INTO Airplanes (type_id, airline_id, tail_number, airplane_status)
VALUES ((SELECT type_id FROM Airplane_Types WHERE airplane_model = 'Concorde'),
        (SELECT airline_id FROM Airlines WHERE iata_code = 'AI'), 
        'VT001AI', 'Retired');

INSERT INTO Airplanes (type_id, airline_id, tail_number, airplane_status)
VALUES ((SELECT type_id FROM Airplane_Types WHERE airplane_model = 'Concorde1'),
        (SELECT airline_id FROM Airlines WHERE iata_code = 'AI'), 
        'VT001AK', 'Active');

select * from Airplanes;

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (1, 2, TO_TIMESTAMP('15.12.2024 10:30', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('15.12.2024 14:15', 'DD.MM.YYYY HH24:MI'), 1, 1, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (2, 3, TO_TIMESTAMP('16.12.2024 09:00', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('16.12.2024 13:00', 'DD.MM.YYYY HH24:MI'), 2, 2, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (3, 1, TO_TIMESTAMP('20.12.2024 06:50', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('20.12.2024 09:30', 'DD.MM.YYYY HH24:MI'), 3, 3, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (1, 4, TO_TIMESTAMP('20.12.2024 18:00', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('21.12.2024 01:15', 'DD.MM.YYYY HH24:MI'), 1, 4, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (5, 2, TO_TIMESTAMP('19.12.2024 14:00', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('19.12.2024 18:30', 'DD.MM.YYYY HH24:MI'), 4, 5, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (2, 1, TO_TIMESTAMP('20.12.2024 08:00', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('20.12.2024 11:45', 'DD.MM.YYYY HH24:MI'), 1, 1, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (3, 5, TO_TIMESTAMP('21.12.2024 22:30', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('22.12.2024 05:50', 'DD.MM.YYYY HH24:MI'), 2, 2, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (1, 3, TO_TIMESTAMP('23.12.2024 13:20', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('23.12.2024 16:40', 'DD.MM.YYYY HH24:MI'), 3, 3, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (4, 1, TO_TIMESTAMP('24.12.2024 07:15', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('24.12.2024 10:35', 'DD.MM.YYYY HH24:MI'), 2, 4, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (5, 3, TO_TIMESTAMP('25.12.2024 15:00', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('25.12.2024 19:45', 'DD.MM.YYYY HH24:MI'), 1, 5, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (1, 2, TO_TIMESTAMP('26.12.2024 12:00', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('26.12.2024 14:30', 'DD.MM.YYYY HH24:MI'), 4, 1, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (2, 4, TO_TIMESTAMP('27.12.2024 11:00', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('27.12.2024 15:20', 'DD.MM.YYYY HH24:MI'), 3, 2, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (5, 1, TO_TIMESTAMP('28.12.2024 17:10', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('28.12.2024 20:45', 'DD.MM.YYYY HH24:MI'), 2, 3, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (1, 4, TO_TIMESTAMP('29.12.2024 16:40', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('30.12.2024 02:10', 'DD.MM.YYYY HH24:MI'), 1, 4, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (2, 3, TO_TIMESTAMP('30.12.2024 06:00', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('30.12.2024 08:35', 'DD.MM.YYYY HH24:MI'), 4, 5, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (1, 5, TO_TIMESTAMP('31.12.2024 09:30', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('31.12.2024 14:00', 'DD.MM.YYYY HH24:MI'), 1, 1, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (5, 4, TO_TIMESTAMP('13.12.2024 22:10', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('14.12.2024 01:50', 'DD.MM.YYYY HH24:MI'), 2, 2, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (4, 2, TO_TIMESTAMP('01.01.2025 10:20', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('01.01.2025 15:30', 'DD.MM.YYYY HH24:MI'), 3, 3, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (3, 1, TO_TIMESTAMP('02.01.2025 18:40', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('03.01.2025 02:10', 'DD.MM.YYYY HH24:MI'), 4, 4, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (2, 5, TO_TIMESTAMP('03.01.2025 11:00', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('03.01.2025 14:30', 'DD.MM.YYYY HH24:MI'), 1, 5, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (1, 3, TO_TIMESTAMP('04.01.2025 08:00', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('04.01.2025 10:50', 'DD.MM.YYYY HH24:MI'), 2, 1, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (2, 4, TO_TIMESTAMP('05.01.2025 13:30', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('05.01.2025 18:10', 'DD.MM.YYYY HH24:MI'), 3, 2, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (5, 3, TO_TIMESTAMP('06.01.2025 15:10', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('06.01.2025 18:50', 'DD.MM.YYYY HH24:MI'), 4, 3, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (1, 5, TO_TIMESTAMP('07.01.2025 08:50', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('07.01.2025 13:40', 'DD.MM.YYYY HH24:MI'), 1, 4, 'Scheduled');

INSERT INTO Flights (departure_airport_id, arrival_airport_id, departure_time, arrival_time, airline_id, airplane_id, flight_status) 
VALUES (1, 5, TO_TIMESTAMP('07.01.2025 08:50', 'DD.MM.YYYY HH24:MI'), TO_TIMESTAMP('07.01.2025 13:40', 'DD.MM.YYYY HH24:MI'), 1, 11, 'Scheduled');

select * from Flights;

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (1, '1A', 150, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (1, '1B', 150, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (1, '1C', 150, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (2, '1A', 180, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (2, '1B', 180, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (2, '1C', 180, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (3, '1A', 220, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (3, '1B', 220, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (3, '1C', 220, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (4, '1A', 200, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (4, '1B', 200, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (4, '1C', 200, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (5, '1A', 210, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (5, '1B', 210, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (5, '1C', 210, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (6, '1A', 250, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (6, '1B', 250, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (6, '1C', 250, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (7, '1A', 300, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (7, '1B', 300, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (7, '1C', 300, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (8, '1A', 190, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (8, '1B', 190, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (8, '1C', 190, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (9, '1A', 170, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (9, '1B', 170, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (9, '1C', 170, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (10, '1A', 250, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (10, '1B', 250, 'Economy', 'Available');

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status) 
VALUES (10, '1C', 250, 'Economy', 'Available');

-- Билеты с установленным passenger_id, purchase_date и ticket_status = 'Booked'
INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (1, '2A', 150, 'Economy', 'Booked', 1, TO_TIMESTAMP('10.01.2024 14:30', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (2, '2A', 180, 'Economy', 'Booked', 2, TO_TIMESTAMP('15.02.2024 16:45', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (3, '2A', 220, 'Economy', 'Booked', 3, TO_TIMESTAMP('22.03.2024 10:00', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (4, '2A', 200, 'Economy', 'Booked', 4, TO_TIMESTAMP('05.04.2024 12:15', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (5, '2A', 210, 'Economy', 'Booked', 5, TO_TIMESTAMP('12.05.2024 13:30', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (6, '2A', 250, 'Economy', 'Booked', 6, TO_TIMESTAMP('17.06.2024 11:00', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (7, '2A', 300, 'Economy', 'Booked', 7, TO_TIMESTAMP('19.07.2024 09:00', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (8, '2A', 190, 'Economy', 'Booked', 8, TO_TIMESTAMP('25.08.2024 17:30', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (9, '2A', 170, 'Economy', 'Booked', 9, TO_TIMESTAMP('30.09.2024 08:45', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (10, '2A', 250, 'Economy', 'Booked', 10, TO_TIMESTAMP('01.10.2024 20:00', 'DD.MM.YYYY HH24:MI'));

-- Additional Booked Tickets for Flight 1
INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (1, '3A', 150, 'Economy', 'Booked', 1, TO_TIMESTAMP('15.01.2024 14:30', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (1, '3B', 150, 'Economy', 'Booked', 2, TO_TIMESTAMP('16.01.2024 15:45', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (1, '3C', 150, 'Economy', 'Booked', 3, TO_TIMESTAMP('17.01.2024 10:00', 'DD.MM.YYYY HH24:MI'));


-- Additional Booked Tickets for Flight 2
INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (2, '3A', 180, 'Economy', 'Booked', 4, TO_TIMESTAMP('18.01.2024 16:30', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (2, '3B', 180, 'Economy', 'Booked', 5, TO_TIMESTAMP('19.01.2024 17:45', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (2, '3C', 180, 'Economy', 'Booked', 6, TO_TIMESTAMP('20.01.2024 12:00', 'DD.MM.YYYY HH24:MI'));

-- Additional Booked Tickets for Flight 3
INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (3, '3A', 220, 'Economy', 'Booked', 7, TO_TIMESTAMP('21.01.2024 11:15', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (3, '3B', 220, 'Economy', 'Booked', 8, TO_TIMESTAMP('22.01.2024 14:00', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (3, '3C', 220, 'Economy', 'Booked', 9, TO_TIMESTAMP('23.01.2024 09:30', 'DD.MM.YYYY HH24:MI'));

-- Additional Booked Tickets for Flight 4
INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (4, '3A', 200, 'Economy', 'Booked', 10, TO_TIMESTAMP('24.01.2024 18:00', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (4, '3B', 200, 'Economy', 'Booked', 1, TO_TIMESTAMP('25.01.2024 19:00', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (4, '3C', 200, 'Economy', 'Booked', 2, TO_TIMESTAMP('26.01.2024 20:15', 'DD.MM.YYYY HH24:MI'));

-- Additional Booked Tickets for Flight 5
INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (5, '3A', 210, 'Economy', 'Booked', 3, TO_TIMESTAMP('27.01.2024 15:30', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (5, '3B', 210, 'Economy', 'Booked', 4, TO_TIMESTAMP('28.01.2024 16:45', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (5, '3C', 210, 'Economy', 'Booked', 5, TO_TIMESTAMP('29.01.2024 10:30', 'DD.MM.YYYY HH24:MI'));

-- Additional Booked Tickets for Flight 6
INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (6, '3A', 250, 'Economy', 'Booked', 6, TO_TIMESTAMP('30.01.2024 13:00', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (6, '3B', 250, 'Economy', 'Booked', 7, TO_TIMESTAMP('31.01.2024 14:15', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (6, '3C', 250, 'Economy', 'Booked', 8, TO_TIMESTAMP('01.02.2024 09:30', 'DD.MM.YYYY HH24:MI'));

-- Additional Booked Tickets for Flight 7
INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (7, '3A', 300, 'Economy', 'Booked', 9, TO_TIMESTAMP('02.02.2024 17:00', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (7, '3B', 300, 'Economy', 'Booked', 10, TO_TIMESTAMP('03.02.2024 18:15', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (7, '3C', 300, 'Economy', 'Booked', 1, TO_TIMESTAMP('04.02.2024 11:00', 'DD.MM.YYYY HH24:MI'));

-- Additional Booked Tickets for Flight 8
INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (8, '3A', 190, 'Economy', 'Booked', 2, TO_TIMESTAMP('05.02.2024 14:30', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (8, '3B', 190, 'Economy', 'Booked', 3, TO_TIMESTAMP('06.02.2024 15:45', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (8, '3C', 190, 'Economy', 'Booked', 4, TO_TIMESTAMP('07.02.2024 12:00', 'DD.MM.YYYY HH24:MI'));

-- Additional Booked Tickets for Flight 9
INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (9, '3A', 170, 'Economy', 'Booked', 5, TO_TIMESTAMP('08.02.2024 16:30', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (9, '3B', 170, 'Economy', 'Booked', 6, TO_TIMESTAMP('09.02.2024 17:45', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (9, '3C', 170, 'Economy', 'Booked', 7, TO_TIMESTAMP('10.02.2024 10:00', 'DD.MM.YYYY HH24:MI'));

-- Additional Booked Tickets for Flight 10
INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (10, '3A', 250, 'Economy', 'Booked', 8, TO_TIMESTAMP('11.02.2024 19:30', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (10, '3B', 250, 'Economy', 'Booked', 9, TO_TIMESTAMP('12.02.2024 20:45', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (10, '3C', 250, 'Economy', 'Booked', 10, TO_TIMESTAMP('13.02.2024 14:00', 'DD.MM.YYYY HH24:MI'));





INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (5, '3D', 210, 'Economy', 'Booked', 3, TO_TIMESTAMP('27.01.2024 15:30', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (5, '3E', 210, 'Economy', 'Booked', 4, TO_TIMESTAMP('28.01.2024 16:45', 'DD.MM.YYYY HH24:MI'));


-- Additional Booked Tickets for Flight 6
INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (6, '3D', 250, 'Economy', 'Booked', 6, TO_TIMESTAMP('30.01.2024 13:00', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (6, '3E', 250, 'Economy', 'Booked', 7, TO_TIMESTAMP('31.01.2024 14:15', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (6, '3F', 250, 'Economy', 'Booked', 8, TO_TIMESTAMP('01.02.2024 09:30', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (6, '3J', 210, 'Economy', 'Booked', 5, TO_TIMESTAMP('29.01.2024 10:30', 'DD.MM.YYYY HH24:MI'));

-- Additional Booked Tickets for Flight 7
INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (7, '3D', 300, 'Economy', 'Booked', 9, TO_TIMESTAMP('02.02.2024 17:00', 'DD.MM.YYYY HH24:MI'));

INSERT INTO Tickets (flight_id, seat_number, price, ticket_class, ticket_status, passenger_id, purchase_date) 
VALUES (7, '3E', 300, 'Economy', 'Booked', 10, TO_TIMESTAMP('03.02.2024 18:15', 'DD.MM.YYYY HH24:MI'));



-- Insert corresponding Employee records and link to airports
INSERT INTO Employee (user_id, airport_id, job_title, hire_date, salary)
VALUES (11, 3, 'Screening agent', TO_DATE('2022-03-25', 'YYYY-MM-DD'), 45000);

INSERT INTO Employee (user_id, airport_id, job_title, hire_date, salary)
VALUES (12, 1, 'Manager', TO_DATE('2020-06-15', 'YYYY-MM-DD'), 80000);

INSERT INTO Employee (user_id, airport_id, job_title, hire_date, salary)
VALUES (13, 2, 'Customs Officer', TO_DATE('2018-07-20', 'YYYY-MM-DD'), 90000);

INSERT INTO Employee (user_id, airport_id, job_title, hire_date, salary)
VALUES (14, 1, 'Manager', TO_DATE('2021-01-10', 'YYYY-MM-DD'), 50000);

INSERT INTO Employee (user_id, airport_id, job_title, hire_date, salary)
VALUES (15, 2, 'Customs Officer', TO_DATE('2019-12-05', 'YYYY-MM-DD'), 40000);
commit;







